shuangpan5217/2021-fall-cs160-team-Mochi

backend/source/apis/usermgmt/update_password.go

issue
https://github.com/shuangpan5217/2021-fall-cs160-team-Mochi/issues/61

up date user password

---

backend/source/apis/comments/create_comment.go
backend/source/generated/models/comment_response.go
backend/source/generated/restapi/embedded_spec.go
backend/source/swagger-specs/api.yaml

post comment returns comment id

---

backend/source/swagger-specs/api.yaml

add friend api

---

frontend/src/App.js
frontend/src/components/inputBox.jsx
frontend/src/components/loginWindow.jsx
frontend/src/components/signUpWindow.jsx
frontend/src/components/template.jsx
frontend/src/components/uploadNotesWindow.jsx
frontend/src/pages/HomePage.jsx
frontend/src/pages/LoginPage.jsx
frontend/src/pages/SignUpPage.jsx

- added masking to password fields
- added password confirmation function
- called login API after sign up
- added redirection back to login if no auth token is detected (storing auth token in local storage for now until we do cookies; to sign out...temporarily just go back to login/signup page)

misc security changes

---

backend/source/generated/models/comment_object.go
backend/source/generated/restapi/embedded_spec.go
backend/source/swagger-specs/api.yaml

https://github.com/shuangpan5217/2021-fall-cs160-team-Mochi/issues/127

add comment_id to note comments resp

---

backend/source/apis/usermgmt/search_by_username.go
backend/source/generated/restapi/configure_coreapi.go

search by username api implementation

---

backend/source/apis/friends/add_friends.go
backend/source/generated/restapi/configure_coreapi.go

add friends api implementation

---

backend/source/apis/friends/remove_friends.go
backend/source/generated/restapi/configure_coreapi.go

remove friends api implementation

---

backend/source/apis/friends/get_friends.go
backend/source/generated/restapi/configure_coreapi.go

get friends api implementation

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/loginWindow.jsx
frontend/src/components/searchBar.jsx
frontend/src/components/signUpWindow.jsx
frontend/src/components/uploadDropzone.jsx
frontend/src/css/forms.css

- fix signup and login page
- fix uploadDropzone missing dependency problem

fix signup and login

---

backend/source/apis/commonutils/authenticate.go
backend/source/apis/friends/add_friends.go
backend/source/apis/friends/get_friends.go
backend/source/apis/testUtils/testUtils.go
backend/source/apis/usermgmt/login.go
backend/source/apis/usermgmt/update_password.go
backend/source/apis/usermgmt/update_password_test.go
backend/source/apis/usermgmt/update_userInfo.go
backend/source/apis/usermgmt/update_userInfo_test.go
backend/source/generated/cmd/coreapi-server/main.go
backend/source/generated/restapi/configure_coreapi.go
backend/source/generated/restapi/testHelper.go

https://github.com/shuangpan5217/2021-fall-cs160-team-Mochi/issues/158

Test automation for updating user password/profile

---

backend/source/apis/groups/create_group.go
backend/source/generated/restapi/configure_coreapi.go

POST /v1/groups

---

backend/source/apis/notes/post_file_test.go

Backend Testing - post/get single file

---

backend/source/apis/notes/get_single_note.go

none
1. check group users if note is shared with a group
Test using user `pan3`
group_notes
</br>
group_users
</br>
get notes by id for `pan3`

check group user in getting note by note_id

---

backend/source/apis/groups/get_group_info.go
backend/source/generated/restapi/configure_coreapi.go

GET /v1/groups/{group_id}

---

frontend/src/components/infoTab.jsx
frontend/src/components/inputBox.jsx
frontend/src/components/tag.jsx
frontend/src/components/uploadDropzone.jsx
frontend/src/components/uploadNotesWindow.jsx
frontend/src/css/forms.css
frontend/src/css/uploadNotesWindow.css
frontend/src/css/viewNotePage.css
frontend/src/pages/ViewNotesPage.jsx

- updated upload window ui layout
- finished tags ui
- added style ui
- when upload is successful, goes to view note (where style is listed as a tag)

Update upload window

---

backend/source/apis/notes/add_note_members.go
backend/source/apis/notes/delete_note_by_id.go
backend/source/apis/notes/get_file_test.go
backend/source/apis/notes/get_multiple_files.go
backend/source/apis/notes/post_file_test.go
backend/source/apis/testUtils/testUtils.go
backend/source/apis/usermgmt/update_password_test.go
backend/source/apis/usermgmt/update_userInfo_test.go
backend/source/generated/models/note_object_request.go
backend/source/generated/restapi/embedded_spec.go
backend/source/swagger-specs/api.yaml

https://github.com/shuangpan5217/2021-fall-cs160-team-Mochi/issues/157

getfiletest

---

backend/source/apis/userImages/get_user_image.go
backend/source/apis/userImages/upload_user_image.go
backend/source/generated/models/group_members.go
backend/source/generated/models/group_members_object.go
backend/source/generated/models/user_images_response.go
backend/source/generated/restapi/embedded_spec.go
backend/source/generated/restapi/operations/groups_v1/add_group_users_v1_parameters.go
backend/source/generated/restapi/operations/groups_v1/get_group_users_v1_responses.go
backend/source/generated/restapi/operations/groups_v1/remove_group_users_v1_parameters.go
backend/source/swagger-specs/api.yaml

1. array for group member
2. user image. Support jpeg and png
JPEG
</br>
PNG

group members response, fix user image type

---

backend/source/apis/groups/delete_group_by_id.go
backend/source/apis/groups/remove_group_members.go
backend/source/generated/restapi/configure_coreapi.go

remove group users

---

backend/source/apis/groups/get_group_members.go
backend/source/generated/restapi/configure_coreapi.go

get group users

---

backend/source/apis/notes/search_note_by_tags.go

```
SELECT DISTINCT ON (note_reference) note_reference, note_id, description, note_owner, style, tag, title, type, updated_at
FROM "notes"  
WHERE (type = 'public' AND (tag like '%math%' OR title like '%math%' OR description like '%math%') OR (tag like '%m%' OR title like '%m%' OR description like '%m%')) 
ORDER BY note_reference, updated_at 
LIMIT 20 OFFSET 0  
```

add title and description for searching notes query

---

backend/source/generated/restapi/configure_coreapi.go

add allowed http methods

---

backend/source/apis/notes/get_file.go
backend/source/apis/notes/get_multiple_files.go
backend/source/generated/models/get_file_response.go
backend/source/generated/restapi/embedded_spec.go
backend/source/swagger-specs/api.yaml

<b>Get single file</b>
</br></br>
<b>Get multiple files</b>

add note_id and note_reference to file resp

---

frontend/src/components/header.jsx
frontend/src/components/inputBox.jsx
frontend/src/components/personalPrefWindow.jsx
frontend/src/components/profileImage.jsx
frontend/src/components/signUpWindow.jsx
frontend/src/components/template.jsx
frontend/src/components/uploadDropzone.jsx
frontend/src/components/uploadNotesWindow.jsx
frontend/src/pages/PersonalPage.jsx
frontend/src/pages/SignUpPage.jsx

- created personal preference window (click edit profile from the personal page)
- auto-fills personal info to the window
- user info/password/profile images can now be updated/added
Known bug: For larger profile images, the image doesn't automatically update on the page. You need to refresh the page to see the update. I've added this to the icebox.

Personal Preference Window (UI + Connect to Backend)

---

frontend/src/components/addFriendWindow.jsx
frontend/src/components/addMemberWindow.jsx
frontend/src/components/createGroupWindow.jsx
frontend/src/components/modalHeader.jsx
frontend/src/components/noteActions.jsx
frontend/src/components/pdfViewer.jsx
frontend/src/components/sharingTab.jsx
frontend/src/css/forms.css
frontend/src/css/modal.css
frontend/src/css/pdfViewer.css
frontend/src/css/personalPage.css
frontend/src/index.css
frontend/src/pages/GroupPage.jsx
frontend/src/pages/PersonalPage.jsx
frontend/src/pages/SearchResultsPage.jsx

- fix personal page layout
- fix group page layout
- fix add friend window
- fix create group window
- fix nav to group after created
- fix add member window
- fix small panel button spacing
- add multi page pdfs
- show private message
- hide grp page from non members
- hide add member btn for members
- hide edit group btn for members
- add sign out option
- add note info overlay to thumbnails

Misc demo fixes

---

backend.Dockerfile
backend/Dockerfile
backend/source/generated/cmd/coreapi-server/main.go
backend/source/generated/restapi/configure_coreapi.go
docker-compose-backend.yaml

docker compose api and database

backenddocker
